server:
  port: 8001
spring:
  application:
    name: colin-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order
    username: root
    password: root1024
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  profiles:
    active: seata
#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: default_tx_group
#  config:
#    type: nacos
#    nacos:
#      serverAddr: 127.0.0.1:8848
#      dataId: "seataServer.properties"
#      username: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      username: "nacos"
#      password: "nacos"
